import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import IconSideNav from "@/components/sideNav";
import IconHeader from "@/components/iconHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <header style={{display:"flex"}} className="p-2">
          <IconHeader/>
          <button style={{marginLeft:"auto"}} className="transition ease-in-out delay-150 bg-transparent hover:bg-indigo-600 hover:scale-110 duration-300 border border-indigo-600 text-white py-2 px-3 rounded-md">
            <p style={{fontSize:13}}>My Resume</p>
          </button>  
        </header>
        <div className="flex h-screen">
          <IconSideNav/>
          {children}
        </div>
      </body>
    </html>
  );
}
